const site = 'https://ozzyczech.cz';

export default {
	site,
	linksHostname: 'ozzyczech.cz',
	rss: {
		title: "Roman's notes",
		description: 'Personal notes and wiki — ozzyczech.cz',
	},
	starlight: {
		title: "Roman's notes",
		tableOfContents: false,
		pagination: false,
		social: [
			{ icon: 'github', label: 'GitHub', href: 'https://github.com/OzzyCzech/wiki' },
			{ icon: 'stackOverflow', label: 'StackOverflow', href: 'https://meta.stackoverflow.com/users/355316/ozzyczech' },
		],
		head: [
			{ tag: 'link', attrs: { rel: 'alternate', type: 'application/rss+xml', title: "Roman's notes", href: site + '/rss.xml' } },
		],
		customCss: ['./src/style.css'],
		logo: { src: './src/assets/roman-ozana.jpg' },
		editLink: { baseUrl: 'https://github.com/OzzyCzech/wiki/edit/main/' },
		sidebar: [
			{ label: 'Home', link: '/' },
			{
				label: 'AI',
				collapsed: true,
				items: [
					{ label: 'Agents', collapsed: false, items: [{ autogenerate: { directory: 'AI/Agents' } }] },
					{ label: 'Claude Code', collapsed: false, items: [{ autogenerate: { directory: 'AI/Claude Code' } }] },
					{ label: 'Gemma', collapsed: false, items: [{ autogenerate: { directory: 'AI/Gemma' } }] },
					{ label: 'Tools', collapsed: false, items: [{ autogenerate: { directory: 'AI/Tools' } }] },
					{ label: 'Guides', collapsed: false, items: [{ autogenerate: { directory: 'AI/Guides' } }] },
					'ai/benchmarks',
				],
			},
			{ label: 'Development', collapsed: false, items: [{ autogenerate: { directory: 'Development', collapsed: true } }] },
			{ label: 'PHP', collapsed: true, items: [{ autogenerate: { directory: 'PHP' } }] },
			{ label: 'Inspiration', collapsed: true, items: [{ autogenerate: { directory: 'Inspiration', collapsed: false } }] },
			{ label: 'Shell & CLI', collapsed: true, items: [{ autogenerate: { directory: 'CLI', collapsed: true } }] },
			{ label: 'macOS', collapsed: true, items: [{ autogenerate: { directory: 'macOS', collapsed: true } }] },
			{ label: 'Awesome', collapsed: true, items: [{ autogenerate: { directory: 'Awesome', collapsed: false } }] },
			{ label: 'Life Hack', collapsed: true, items: [{ autogenerate: { directory: 'LifeHack' } }] },
			{ label: 'Health', collapsed: true, items: [{ autogenerate: { directory: 'Health' } }] },
			{
				label: 'Photography',
				collapsed: true,
				items: [
					{ label: 'Sony', collapsed: false, items: [{ autogenerate: { directory: 'Photography/Sony', collapsed: false } }] },
					{ label: 'Fujifilm', collapsed: false, items: [{ autogenerate: { directory: 'Photography/Fujifilm', collapsed: false } }] },
					{ label: 'Nikon', collapsed: false, items: [{ autogenerate: { directory: 'Photography/Nikon', collapsed: false } }] },
					{ label: 'Panasonic', collapsed: false, items: [{ autogenerate: { directory: 'Photography/Panasonic', collapsed: false } }] },
					{ label: 'Canon', collapsed: false, items: [{ autogenerate: { directory: 'Photography/Canon', collapsed: false } }] },
					'photography/compact-cameras',
					'photography/action-cameras',
					'photography/photo-hosting',
					{ label: 'Software', collapsed: true, items: [{ autogenerate: { directory: 'Photography/Software', collapsed: true } }] },
					{ label: 'Accessories', collapsed: false, items: [{ autogenerate: { directory: 'Photography/Accessories' } }] },
				],
			},
			{ label: 'Security', collapsed: true, items: [{ autogenerate: { directory: 'Security' } }] },
			{ label: 'Hardware', collapsed: true, items: [{ autogenerate: { directory: 'Hardware', collapsed: true } }] },
			{ label: 'Movies & TV', collapsed: true, items: [{ autogenerate: { directory: 'Movies & TV', collapsed: false } }] },
			{ label: 'Knihy', collapsed: true, items: [{ autogenerate: { directory: 'Knihy' } }] },
			{ label: 'Povídky', collapsed: true, items: [{ autogenerate: { directory: 'Povidky' } }] },
			{ label: 'Cestování', collapsed: true, items: [{ autogenerate: { directory: 'Travel', collapsed: true } }] },
		],
	},
};
